latitude: LATITUDE
longitude: LONGITUDE
gps_lat: LATITUDE_GPS
gps_lon: LONGITUDE_GPS
gps_time: TIME_GPS
ctd_depth: DEPTH
pressure: PRES
conductivity: CNDC
aanderaa4330_dissolved_oxygen: DOXY 
sigma_theta: SIGTHETA
sigma_t: SIGMA_T 
temperature: TEMP
temperature_raw: TEMP_RAW
salinity_raw: PSAL_RAW
conductivity_raw: CNDC_RAW
salinity: PSAL
absolute_salinity: SA
conservative_temperature: CT
ctd_density: DENSITY
potential_temperature: THETA
theta: THETA
potential_density: POTDENS0
 