MOC:
  URI: http://vocab.nerc.ac.uk/collection/P07/current/YQUEEUJE/
  standard_name: ocean_volume_y_transport
MOC_STREAMFUNCTION:
  URI: http://vocab.nerc.ac.uk/collection/P07/current/CFSN0466/
  standard_name: ocean_meridional_overturning_streamfunction
LATITUDE:
  coordinate_reference_frame: urn:ogc:crs:EPSG::4326
  long_name: Latitude north
  observation_type: measured
  platform: platform
  reference: WGS84
  standard_name: latitude
  units: degrees_north
  valid_max: 90
  valid_min: -90
  axis: Y
  URI: https://vocab.nerc.ac.uk/collection/OG1/current/LAT/
LONGITUDE:
  coordinate_reference_frame: urn:ogc:crs:EPSG::4326
  long_name: Longitude east
  observation_type: measured
  platform: platform
  reference: WGS84
  standard_name: longitude
  units: degrees_east
  valid_max: 180
  valid_min: -180
  axis: X
  URI: https://vocab.nerc.ac.uk/collection/OG1/current/LON/
TIME:
  long_name: time of measurement
  observation_type: measured
  standard_name: time
  URI: https://vocab.nerc.ac.uk/collection/P02/current/AYMD/
DEPTH:
  source: pressure
  long_name: glider depth
  standard_name: depth
  units: m
  comment: from science pressure and interpolated
  sensor: sensor_ctd
  observation_type: calculated
  accuracy: 1
  precision: 2
  resolution: 0.02
  platform: platform
  valid_min: 0
  valid_max: 2000
  reference_datum: surface
  positive: down
DEPTH_Z:
  source: pressure
  long_name: glider depth
  standard_name: depth
  units: m
  comment: Defined with positive up
  sensor: sensor_ctd
  observation_type: calculated
  platform: platform
  valid_min: -4000
  valid_max: 0
  reference_datum: surface
  positive: up

CNDC:
  sensor: sensor_ctd
  long_name: Electrical conductivity of the water body by CTD
  observation_type: measured
  standard_name: sea_water_electrical_conductivity
  units: mS cm-1
  valid_max: 85.0
  valid_min: 0.0
  URI: https://vocab.nerc.ac.uk/collection/OG1/current/CNDC/
CNDC_RAW:
  sensor: sensor_ctd
  long_name: Electrical conductivity of the water body by CTD
  observation_type: measured
  standard_name: sea_water_electrical_conductivity
  units: mS cm-1
  valid_max: 85.0
  valid_min: 0.0
  URI: https://vocab.nerc.ac.uk/collection/OG1/current/CNDC/ 
PRES:
  comment: ctd pressure sensor
  sensor: sensor_ctd
  long_name: Pressure (spatial coordinate) exerted by the water body by profiling
    pressure sensor and correction to read zero at sea level
  observation_type: measured
  positive: down
  reference_datum: sea-surface
  standard_name: sea_water_pressure
  units: dbar
  valid_max: 2000
  valid_min: 0
  URI: https://vocab.nerc.ac.uk/collection/OG1/current/PRES
PSAL:
  long_name: water salinity
  standard_name: sea_water_practical_salinity
  units: 1e-3
  comment: Practical salinity of the water body by CTD and computation using UNESCO
    1983 algorithm
  sources: CNDC, TEMP, PRES
  observation_type: calculated
  sensor: sensor_ctd
  valid_max: 40
  valid_min: 0
  URI: https://vocab.nerc.ac.uk/collection/OG1/current/PSAL/
PSAL_RAW:
  long_name: water salinity
  standard_name: sea_water_practical_salinity
  units: 1e-3
  comment: Practical salinity of the water body by CTD and computation using UNESCO
    1983 algorithm
  sources: CNDC, TEMP, PRES
  observation_type: calculated
  sensor: sensor_ctd
  valid_max: 40
  valid_min: 0
  URI: https://vocab.nerc.ac.uk/collection/OG1/current/PSAL/
TEMP:
  long_name: 'Temperature of the water body by CTD '
  observation_type: measured
  standard_name: sea_water_temperature
  units: Celsius
  valid_max: 42
  valid_min: -5
  URI: https://vocab.nerc.ac.uk/collection/OG1/current/TEMP/
TEMP_RAW:
  long_name: 'Temperature of the water body by CTD '
  observation_type: measured
  standard_name: sea_water_temperature
  units: Celsius
  valid_max: 42
  valid_min: -5
  URI: https://vocab.nerc.ac.uk/collection/OG1/current/TEMP/
THETA:
  long_name: Potential temperature of the water body by computation using UNESCO 1983
    algorithm.
  observation_type: calculated
  sources: salinity temperature pressure
  standard_name: sea_water_potential_temperature
  units: Celsius
  valid_max: 42
  valid_min: -5
  URI: https://vocab.nerc.ac.uk/collection/OG1/current/THETA/
POTDENS0:
  long_name: Potential density of water body at surface
  standard_name: sea_water_potential_density
  units: kg m-3
  observation_type: calculated
  sources: salinity temperature pressure
  valid_min: 1000
  valid_max: 1040
  URI: https://vocab.nerc.ac.uk/collection/OG1/current/POTDENS0/
SIGTHETA:
  long_name: Sigma-theta
  standard_name: sea_water_sigma_theta
  units: kg m-3
  observation_type: calculated
  sources: salinity temperature pressure
  valid_min: 0
  valid_max: 50
  URI: https://vocab.nerc.ac.uk/collection/OG1/current/SIGTHETA/
SIGMA_T:
  long_name: Sigma-t
  standard_name: sea_water_sigma_t
  units: kg m-3
  observation_type: calculated
  sources: salinity temperature pressure
  valid_min: 0
  valid_max: 50
  URI: https://vocab.nerc.ac.uk/collection/OG1/current/SIGMA_T/
DENSITY:
  long_name: The mass of a unit volume of any body of fresh or salt water
  standard_name: sea_water_density
  units: kg m-3
  comment: raw, uncorrected salinity
  observation_type: calculated
  sources: salinity temperature pressure
  valid_min: 1000
  valid_max: 1040
  URI: https://vocab.nerc.ac.uk/collection/OG1/current/DENSITY/
